# Generated by Django 5.2.4 on 2026-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'],
                     'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub ссылка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(
                max_length=200, verbose_name='Название проекта'),
        ),
    ]
