# Generated by Django 5.2.4 on 2026-06-03 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects',
         '0002_alter_skill_options_alter_project_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 related_name='owned_projects',
                 to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(
                blank=True, related_name='participated_projects',
                 to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(
                blank=True, related_name='projects',
                 to='projects.skill', verbose_name='Необходимые навыки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), (
                'closed', 'Закрыт')], default='open', max_length=6,
                  verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(
                max_length=100, unique=True, verbose_name='Название навыка'),
        ),
    ]
