"""Константы для проекта TeamFinder"""

# Модель Skill
SKILL_NAME_MAX_LENGTH = 124

# Модель Project
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

# Модель User
USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

# Пагинация
PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12
# API
SKILLS_SEARCH_LIMIT = 10
