"""Константы для проекта TeamFinder"""

# Модель Skill
SKILL_NAME_MAX_LENGTH = 124

# Модель Project
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

# Модель User
USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

# Аватар
AVATAR_SIZE = 100
AVATAR_FONT_SIZE = 50
AVATAR_TEXT_COLOR = 'white'

# Цвета для аватара
COLOR_STEEL_BLUE = (70, 130, 180)
COLOR_MEDIUM_SEA_GREEN = (60, 179, 113)
COLOR_GOLDENROD = (218, 165, 32)
COLOR_SLATE_BLUE = (106, 90, 205)
COLOR_CRIMSON = (220, 20, 60)
COLOR_TOMATO = (255, 99, 71)
COLOR_INDIGO = (75, 0, 130)
COLOR_CORNFLOWER_BLUE = (100, 149, 237)
COLOR_MEDIUM_SLATE_BLUE = (123, 104, 238)

AVATAR_COLORS = [
    COLOR_STEEL_BLUE,
    COLOR_MEDIUM_SEA_GREEN,
    COLOR_GOLDENROD,
    COLOR_SLATE_BLUE,
    COLOR_CRIMSON,
    COLOR_TOMATO,
    COLOR_INDIGO,
    COLOR_CORNFLOWER_BLUE,
    COLOR_MEDIUM_SLATE_BLUE,
]

# Пагинация
PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12

# API
SKILLS_SEARCH_LIMIT = 10
